### ISSUE TITLE
org.openqa.selenium.SessionNotCreatedException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.

### ISSUE THREAD

**Issue by dipakkumar1225** [LambdaTest/LT-appium-java-testng#7]
With Appium java-client 8.1.1, I am getting invalid address of the remote server

`String hub = "https://" + System.getenv("LT_USERNAME") + ":" + System.getenv("LT_ACCESS_KEY") + "@mobile-hub.lambdatest.com/wd/hub`

This is working perfectly with java-client  7.6.0

**Comment by sriman7849** [comment]
This is the same problem still facing after a year, there are version compatibility issues with the code, requesting the maintainers to look into the same.

**Comment by mykaustubh** [comment]
This has been resolved the issue was from the SCRIPTING PART.
